### ISSUE TITLE
Add random blinking to the characters

### ISSUE THREAD

**Issue by SandrinePDR** [Project-Pandora-Game/pandora#143]
To make the characters look more lively, a random blink should be added to them.
The average human blinks 10 to 15 times per minute, so a random period of time between 4 to 6 seconds after a blink would look natural.

**Comment by Jomshir98** [comment]
This involves following changes:
- Create a new `AtomicCondition` type for "is during blink"
- Add it to the `AppearanceConditionEvaluator`
- Add a mechanism for saying if character is currently blinking using a React hook (so must be deterministic and declarative, but can be randomized on character load)
- Add image overrides to eye assets using this condition (separate asset PR)

While this issue is not architecturally complex, it involves more complex work by working with two repos at the same time. Creating an efficient hook for the condition evaluator to work properly might also be slightly more complex. Feel free to poke me for help with this, as I'm closely familiar with all parts of this.

**Comment by ClaudiaMia** [comment]
I assigned the ticket to you just now Zoe (for you), just so others can see that you are working on this and do not accidentally start working on it, too.

Of course, it is not good practice to assign others, so I just did it this time since you anyway already started work on it~

**Comment by zoe-64** [comment]
Thank you

**Comment by zoe-64** [comment]
I'm going to leave this issue for someone else since I am unable to complete it at this time.
