### ISSUE TITLE
Advanced permission system

### ISSUE THREAD

**Issue by Jomshir98** [Project-Pandora-Game/pandora#17]
See BCX authority module

EDIT 01-2024:

As there was not much of a description of this issue, Jomshir and me chatted about what we want to achieve here until the beta milestone:

We want to add some more permissions first and foremost:

 - [X] interacting with locks/lock slots on worn items
 - [X] interacting with storage module slots on worn items
 - [X] interacting with configuration module slots on worn items
 - [x] changing the color of worn items
 - [x] permission to add and remove favorite-limited items
 - [x] permission to add and remove normal-limited items
 - [x] permission to add and remove maybe-limited items
 -  -/- ~~permission to also interact according to the other granted permissions while the own character is offline~~ --> Edit: Removed, see comments below

Next, we want the ability to set each permission to either Allow, Prompt, or Deny, one time as global default for this user and once per added character ID individually, but we would tailor which of the three are actually available to pick globally, per permission:
E.g. only allow Allow/Deny for permission to interact while you are offline, as prompt makes no sense, or only Prompt/Deny for all permission related to adding/removing items to not allow full open public settings which are unhealthy for a roleplaying community, so that you can only give an "Allow" to individual character IDs.

Prompt will not block an interaction, but when it is triggered, the effect is kept in a queue and a prompt will open for the other user which lists all the permissions that are requested from the other character. This interactive prompt will have the options:
Allow (and remember)
Allow once
Deny once
Deny (and remember)

 - [x] character based permission overrides
 - [x] prompt option

Then we need to carefully select meaningful global defaults between Allow, Prompt, or Deny for each permission to enable a bit better new player safety, but a second step in that venture is to also limit some items per default (not via permission, but via item preferences), such as all combination/password locks.

 - [x] asset preference defaults

Another important piece is for the server to only accept new character IDs in the "Allow" category for permissions, when this character is in the same room. Also, we should define a limit on what percentage of all characters IDs in Pandora would be reasonable to have added for a single permission.

 - [x] limit character IDs

Roles are not really needed.

**Comment by ClaudiaMia** [comment]
I want to note that the tick-boxes are actually not fully done so far as the permission system does not yet support different allow/prompt/deny choices per permission, but only allow/deny for every permission.

The current implementation is not sufficient for beta in my view. Just as a note.

**Comment by ClaudiaMia** [comment]
One more comment about the "permission to also interact according to the other granted permissions while the own character is offline".

I feel this might need some more complex considerations.

Imagine the following scenario:

- A and B play in a private space.
- B enters a room device and A locks B into it.
- B goes suddenly offline due to Internet loss or some super urgent interruption, which is a not too unlikely occurrence
- at this point, there is no longer an owner or admin inside the room who could store the device to free B
- B cannot interact with the lock due to B's offline permission
- B logs in again, is alone and locked into a room and is forced to use safemode which prevents B from playing for one hour -> really unpleasant situation

I see two possible solutions:

1. There would be no permission that prevents someone from unlocking the lock of an offline person. Additionally, you could always change the modules of room devices offline people are in, unless a lock prevents that, but you could not remove them from the slot while they are offline.
2. The creator of (and maybe also the last person editing/touching) the lock could always unlock and remove the lock of offline characters as the permission will be made to not block this case. Additionally, you could always change the modules of room devices offline people are in, unless a lock prevents that, but you could not remove them from the slot while they are offline.

Thoughts?

**Comment by ClaudiaMia** [comment]
One more detail about the "prompt" setting:

I learned that it is quite likely with how settings are currently structured and layered, that a user will need multiple permissions to do something. If the user would need two permissions that are configured to "prompt" the target and one permission that is set to "deny", then I believe the target-user should get no popup at all, as it makes no sense and would just be confusing. Instead we should give a better descriptive toast to the one trying to do a certain interaction. Or even better, that source character could not even try the interaction that will fail because one required permission is set to "deny".

**Comment by Jomshir98** [comment]
This issue has been recently updated quite a bit to reflect the current state and the direction we currently prefer - for anyone interested in it, I recommend reading it from the beginning again.

**Comment by ClaudiaMia** [comment]
I have two more discussion points to this issue:

1. About character based permission overrides: 

- Naturally, if a permission is set to generally deny, you want to define exceptions for characters for whom this permission is allowed. Do we also want to have the option to set individual characters to "prompt"?
- If a permission is set to generally prompt, we naturally, want to define exceptions for characters for whom this permission is allowed. Denying individual characters this permission does not make sense to me, as we have the general blacklist for this, right?
- If a permission is set to generally allow, denying individual characters this permission does not make sense to me, as we have the general blacklist for this. But maybe it makes sense to have the option to set individual characters to "prompt"?

2. The current "Item Limits" section of the permissions seems to allow others to add for instance items marked as "maybe", but also gates who is able to interact with them (I understand that as changing modules on them, or being able to remove them).
Does this make sense? Because that would mean that when you want to strip someone as part of a roleplay, it could be the case that you suddenly cannot remove the bra, because it was a "maybe" item added by some other permitted person before.
This might be intentionally, but could also be a great annoyance as it is an asymmetric behavior and leads to not obvious, unexpected situations.

This boils down to how users understand the item limit features and set it up:
Currently, we expect someone who has normal permission to also has favorite permission, in order to be able to use normal marked items.
But maybe a user thinks that favorite means these are the cosplay items that they feel are more important then others and they do not want others to remove them.

I wonder if the terms are misleading:
The idea behind the term "maybe" was clearly that you feel these items are close to your limit and you are not fully comfortable with someone using them and therefore you only allow special people to use this item.
But what if someone wants to use this category to protect their most favorite items that they do not want most others to touch and remove to protect them, such as a tail, or animal ears. In that sense favorite vs. maybe could be misleading and confusing.

So maybe these three permission should only gate who is allowed to add them and to interact with modules on them, but NOT the permission to remove such items?

Maybe for the protection case, we need a 4th preference category "protected" (shield icon) which is the permission to add/interact/remove items marked as such?

**Comment by Jomshir98** [comment]
I agree with the first part, but second part has nothing to do with the permission system itself - it is about the implementation of "item preferences"/"item limits" and should be discussed completely separately from permissions framework.

For the per-character permissions implementation copying the final outcome of discussion on Discord:
- [ ] Implement character-specific Allow/Prompt/Deny - Each character id can be assigned one of these and it takes precedence over the default permission's setting
- [ ] Implement "Prompt" setting and the prompt itself
- [ ] Add option to forbid defaulting to "Allow" for a specific permission (only the master interact permission would have this used)
[ beta milestone met by the above ]
- [ ] Add options for prompt to result in a session-only Allow/Deny (resets when either of the characters leaves the space the permission was allowed in)
- Collect feedback and adjust if needed

For the "Prompt" implementation the initial implementation could work like this:
- The button on domme's side is yellow, indicating there is nothing stopping her, but there is "prompt" that will need to be approved
  - Hovering over the button shows floating dialog that explains what will happen and lists which permissions are currently missing and will be prompted
- Domme clicks the button
  - [optional] Domme gets a dialog that explains this mechanic and asks for confirmation. If implemented it should be possible to disable this dialog
- Action is normally sent to the server
- Server processes the action:
 - It processes it as normal and discovers the need for "prompt"
 - The action is not performed
 - A prompt request is sent to the sub's client (if there is one connected), telling it:
   - Who requested the permissions
   - [optionally] Description of the actual action (e.g. "Adding Yoke on you")
   - List of all permissions being prompted
 - A result is immediately sent back to domme telling her "access was requested". If the send of request to sub's client failed (e.g. not currently connected or even offline) the message instead says "cannot request permission as target is currently offline, try again later".
- Domme gets toast explaining the result
- Sub's client shows the prompt and then (if prompt is approved) will use the standard permission API to add the character as allow for relevant permission.
  - This will trigger `somethingChanged: permissions` from the server
  - This will make domme's client refresh permission cache
  - This will make the color appear white instead of yellow
- Domme can try again (no auto-retry after approve)

**Comment by Sekkmer** [comment]
I feel these points don't need to be part of Beta 1 and should be moved to a separate issue:

1. Add options for prompt to result in a session-only Allow/Deny (resets when either of the characters leaves the space the permission was allowed in)

2. Allow / Deny once

so as any other [optional] ideas should be collected to a separate issue
