### ISSUE TITLE
exit from room device before leave

### ISSUE THREAD

**Issue by Sekkmer** [Project-Pandora-Game/pandora#370]
solution 1: Automatic
If the device cannot be exited, an error message should be shown to the user

solution 2: Manual
require the user to leave any device before exiting the room

**Comment by Jomshir98** [comment]
Solution number 2 should be easy to implement. All it needs is updating `roomCheckCanLeave` message and its handler `handleRoomCheckCanLeave` on shard and following trail of errors and fixing them one by one. The handler already contains example on how to query data on character's state, as it already checks for items restricting leaving the room.
On client side this would involve updating `CharRoomLeaveInner` component in similar way, using `blockRoomLeave` as example once more.

Alternative way to solve this would be making room devices auto-add `blockRoomLeave` effect, but that is less user-friendly as it couldn't result in a custom message about why character cannot leave except "An item is preventing you from leaving the room."

Solution number 1 would be harder to do cleanly at the moment, as messages to check if character can leave and actual leave procedure are asynchronous and separate. So easiest way to implement automatic leaving would be having client do the two actions (leave device and then leave room) instead of server handling it. This makes solution 1 an extension of solution 2. (and I don't think solution 1 is necessary to do at this point)
